import Head from 'next/head'
import Image from "next/legacy/image"
import styles from '../styles/Home.module.css'
import Navbar from '../Components/component_navbar/Navbar';
import { global } from 'styled-jsx/css';

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <main className={styles.main}>
        <div className="mb-4">
          <Image src="/LogoNetDoc.png" alt="NetDoc Logo" width={120} height={120} />
        </div>


        <h1 className={styles.title}>
          <b>Welcome to <a>NetDoc</a></b>
        </h1>
        <p className={styles.description}>
          Get started by create your network documentation
        </p>

        <div className="flex flex-col items-center space-y-4">

          <div className="border p-14 pt-4 pb-1 border-white-500 flex flex-col items-center space-y-0 rounded-xl">

            <p className="text-white">Server</p>

            <div className="flex justify-center space-x-4">
              <div className="bg-blue-500 text-white p-2 rounded">Ruter</div>
            </div>

            <span className="">port:1</span>

            <div className="w-0.5 bg-gray-400 h-16 align-middle">
              <div>
                <span className="mx-2">vlan1</span>
              </div>
              <div>
                <span className="mx-2">vlan2</span>
              </div>
            </div>

            <span className="mx-2">port:8</span>
            <div className="flex justify-center space-x-4">
              <div className="bg-green-500 text-white p-2 rounded">Switch</div>
            </div>
            <span className="mx-2">port:2 port:3 </span>

          </div>

          <div className="flex justify-center space-x-12">

            <div className="w-0.5 bg-gray-400 m h-16 align-middle">
              <span className="mx-2">vlan1</span>
            </div>

            <div className="w-0.5 bg-gray-400 h-16 align-middle">
              <span className="mx-2">vlan2</span>
            </div>

          </div>

          <div className="flex flex-wrap  justify-center space-x-4">

            <div className="flex flex-col   space-y-4 ">
              <div className='border p-1 pt-1 pb-1 rounded-xl'>
                <p className="text-white">Office</p>
                <div className=" bg-yellow-500 text-white p-2 rounded">Printer</div>
              </div>
            </div>

            <div className="flex flex-col   space-y-4 ">
              <div className='border p-1 pt-1 pb-1 rounded-xl'>
                <p className="text-white">Meeetings</p>
                <div className=" bg-purple-500 text-white p-2 rounded">PC</div>
              </div>
            </div>
          </div>


        </div>

        <div className="p-6 w-full sm:w-3/4 md:w-2/3 lg:w-1/2 xl:w-1/3 mt-10 mx-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
          <div>
            <div className="text-xl font-medium text-black">NetDoc</div>
            <p className="text-gray-500">It is a network documentation application that facilitates the management and tracking of your network infrastructure. With an intuitive user interface and powerful features, NetDoc allows you to create, update, and visualize your network documentation efficiently.</p>
            <p className="text-gray-500">The logic of the application is based on four main parts: Locations, Networks, Devices, and Connections.</p>
            <ul className="list-disc list-inside text-gray-500">
              <li><strong>Locations</strong>: Here you can define and manage the different physical locations of devices connected to the network. Each location can have multiple associated devices.</li>
              <li><strong>Networks</strong>: This section allows you to define different networks.</li>
              <li><strong>Devices</strong>: Here you can add and manage all devices in your network. To follow the logic of a network, we first need to define if it is an infrastructure device, those that allow other equipment to have a connection and manage the network (Switch, Router, Hub, etc.). Then we have endpoints (Printers, Computers, Servers, Internet-of-Things (IoT) devices, etc.)</li>
              <li><strong>Connections</strong>: This part allows you to define connections between different devices in your network. You can specify details such as the type of connection, VLANs, from which to which port it is connected, and the configuration of this: tagged, untagged, undefined.</li>
            </ul>
            <p className="text-gray-500">To start using NetDoc, simply navigate to the My Network section of the application and follow the instructions to add your first location, network, device, and connection. As you add more details to your network documentation, NetDoc will provide you with a clear and updated view of your network infrastructure.</p>
          </div>
        </div>

      </main>



      <footer className={styles.footer}>
        <a
          href="https://netdoc.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/logoFooter.png" alt="Nil Projects logo" width={100} height={100} />
          </span>
          Powered by Nil Piñana{' '}

        </a>
      </footer>
    </div>
  );
}
