import Head from 'next/head'
import Image from "next/legacy/image"
import styles from '../styles/Home.module.css'
import Navbar from '../Components/component_navbar/Navbar';
import { global } from 'styled-jsx/css';

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar/>
      </div>
      <main className={styles.main}>
        <div className="mb-4">
          <Image src="/LogoNetDoc.png" alt="NetDoc Logo" width={120} height={120} />
        </div>

        
        <h1 className={styles.title }>
          <b>Welcome to <a>NetDoc</a></b>
        </h1>
        <p className={styles.description}>
          Get started by create your network documentation
        </p>

        <div className="flex flex-col items-center space-y-4">
          <div className=" flex flex-col items-center space-y-4">
            <div className="flex justify-center space-x-4">
              <div className="bg-blue-500 text-white p-2 rounded">Ruter (Puerto 1)</div>
            </div>
            <div className="w-0.5 bg-gray-400 h-16 align-middle"> 
              <span className="mx-2">port:1</span><br></br>
              <span className="mx-2">vlan1,vlan2</span><br></br>
              <span className="mx-2">port:8</span><br></br>
            </div>
            <div className="flex justify-center space-x-4">
              <div className="bg-green-500 text-white p-2 rounded">Switch (Puerto 8)</div>
            </div>
          </div>

          <div className="flex justify-center space-x-12">
            <div className="w-0.5 bg-gray-400 m h-16 align-middle"></div>

            <div className="w-0.5 bg-gray-400 h-16 align-middle"></div>
          </div>
          <div className="flex justify-center space-x-4">
          
          <div className="flex flex-wrap justify-center space-x-4">
            <div className="flex flex-col space-y-4">
              <div className="bg-red-500 text-white p-2 rounded">PC (VLAN 1, Office)</div>
              <div className="bg-yellow-500 text-white p-2 rounded">Impresora (VLAN 1, Office)</div>
            </div>
            <div className="flex flex-col space-y-4">
              <div className="bg-purple-500 text-white p-2 rounded">PC (VLAN 2, Meetings)</div>
              <div></div>
            </div>
          </div>

          </div>
        </div>

        <div className="p-6 w-2/3 mt-10 mx-auto mt- bg-white rounded-xl shadow-md flex items-center space-x-4">
          <div>
            <div className="text-xl font-medium text-black">NetDoc</div>
            <p className="text-gray-500">És una aplicació de documentació de xarxes que facilita la gestió i el seguiment de la vostra infraestructura de xarxa. Amb una interfície d'usuari intuïtiva i funcions potents, NetDoc us permet crear, actualitzar i visualitzar la vostra documentació de xarxa de manera eficient.</p>
            <p className="text-gray-500">La lògica de l'aplicació es basa en quatre parts principals: Ubicacions, Xarxes, Dispositius i Connexions.</p>
            <ul className="list-disc list-inside text-gray-500">
              <li><strong>Ubicacions</strong>: Aquí podeu definir i gestionar les diferents ubicacions físiques de la vostra infraestructura de xarxa. Cada ubicació pot tenir múltiples xarxes i dispositius associats.</li>
              <li><strong>Xarxes</strong>: Aquesta secció us permet definir les diferents xarxes dins de cada ubicació. Podeu especificar detalls com l'adreça IP, la màscara de subxarxa, el gateway, etc.</li>
              <li><strong>Dispositius</strong>: Aquí podeu afegir i gestionar tots els dispositius de la vostra xarxa. Cada dispositiu pot tenir informació detallada com el fabricant, el model, l'adreça IP, etc.</li>
              <li><strong>Connexions</strong>: Aquesta part us permet definir les connexions entre els diferents dispositius de la vostra xarxa. Podeu especificar detalls com el tipus de connexió, la velocitat, el port, etc.</li>
            </ul>
            <p className="text-gray-500">Per començar a utilitzar NetDoc, simplement heu de navegar a la My Network de l'aplicació i seguir les indicacions per afegir la vostra primera ubicació, xarxa, dispositiu i connexió. A mesura que afegiu més detalls a la vostra documentació de xarxa, NetDoc us proporcionarà una visió clara i actualitzada de la vostra infraestructura de xarxa.</p>
          </div>
        </div>

      </main>



      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >          
        <span className={styles.logo}>
          <Image src="/logoFooter.png" alt="Vercel Logo" width={100} height={100} />
        </span>
          Powered by Nil Piñana{' '}

        </a>
      </footer>
    </div>
  );
}
